// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"book_keeper/internal/config"
	"book_keeper/internal/file"
	"book_keeper/internal/health"
	"book_keeper/internal/mongo"
	"book_keeper/internal/server"
)

// Injectors from di.go:

func InitDependencies() (ServerDependencies, error) {
	configConfig := config.GetConfig()
	serverServer := server.NewServer(configConfig)
	handler := health.NewHandler()
	mongoConfig := config.GetMongoConfigToInject()
	client := mongo.NewClient(mongoConfig)
	fileHandler := file.NewHandler(client)
	handlers := server.Handlers{
		HealthHandler: handler,
		FileHandler:   fileHandler,
	}
	serverDependencies := ServerDependencies{
		config:   configConfig,
		server:   serverServer,
		handlers: handlers,
	}
	return serverDependencies, nil
}

// di.go:

type ServerDependencies struct {
	config   *config.Config
	server   *server.Server
	handlers server.Handlers
}
