name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push-image-to-ghcr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/jenish-jain/book_keeper:latest
          docker push ghcr.io/jenish-jain/book_keeper:latest